# Generated by Django 4.1.1 on 2022-10-04 14:15

import ckeditor.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100, verbose_name='размер')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размер',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='product/%Y/%m/%d', verbose_name='Изображение')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('article', models.SlugField(unique=True, verbose_name='Артикул товара')),
                ('likes', models.IntegerField(default=0, verbose_name='лайки')),
                ('description', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('number', models.IntegerField(verbose_name='количество в линейке')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=100, verbose_name='cкидка')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Неактуальная цена')),
                ('bestseller', models.BooleanField(default=False, verbose_name='Бестселлер')),
                ('novelty', models.BooleanField(default=False, verbose_name='новинки')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Цвет товара')),
                ('size', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog_api.size', verbose_name='размер')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Количество товара')),
                ('lines', models.IntegerField(verbose_name='Линейка')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=100)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Общая цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_api.product', verbose_name='Товар')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('size', models.CharField(max_length=255)),
                ('max_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_api.product')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
