# Generated by Django 4.1.1 on 2022-10-04 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_api', '0002_size_product_cartproduct_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='brand/%Y/%m/%d', verbose_name='Бренд')),
                ('title', models.CharField(max_length=255, verbose_name='Имя-бренда')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_api.product')),
            ],
        ),
    ]
