# Generated by Django 4.1.1 on 2022-10-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_api', '0003_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(max_length=255, verbose_name='ССылка на whatsapp')),
                ('telegram', models.CharField(max_length=255, verbose_name='ССылка на telegram')),
            ],
            options={
                'verbose_name': 'Соц. сети',
                'verbose_name_plural': 'Соц. сети',
            },
        ),
    ]
